version: '3'

services:

  snifr:
    build: '.'
    ports:
      - '1030:1030'
    command: 'python collector/snifr.py'
    depends_on:
      - postgres
      - redis

  postgres:
    container_name: 'postgres'
    image: 'postgres:11'
    environment:
      POSTGRES_DB: gps_teltonika_server
      POSTGRES_USER: gps_teltonika
      POSTGRES_PASSWORD: gps_teltonika
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
      - ./conf/db.sql:/docker-entrypoint-initdb.d/dummy_dump.sql

  redis:
    container_name: 'redis'
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - 'redisdata:/data'

volumes:
  pgdata:
  redisdata:
